version: '3.3'
services:
  backend:
    image: radiobackend
    build: .
    ports:
      - "8801:8801"
    restart: unless-stopped
  mpd:
    image: vimagick/mpd
    ports:
      - "8802:6600"
      - "8800:8800"
    volumes:
      - '/var/radio/config:/root/.config'
      - '/var/radio/music:/root/music'
      - '/var/radio/playlists:/root/playlists'
    restart: unless-stopped
